global.app=require('express')()
app.use(require("body-parser").json({ type: 'application/json' }))
   .use(require('serve-static')('public'))
   .listen(3400)
require('./api')
console.log('http://localhost:3400')